image: hugomods/hugo:exts

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

pages:
  stage: deploy
  script:
    - hugo --gc --minify --cleanDestinationDir --source docs-site --destination public --baseURL "${CI_PAGES_URL}/"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
